public enum EUnitFloatStats 
{ 
    //Base
    MaxHealth,
    BaseArmorPercent,
    MaxArmorPercent,
    Damage,
    CritMultiplierPercent,
    CritChancePercent,
    AttackSpeedPercent,
    MovementSpeed,
    SightRange,
    AttackRange,
    ChaseSpeedPercentMultiplier,
    //Cavalry
    ChargeEndDistance,
    //Traverse
    TraverseSpeedPercentMultiplier,
    //Flying
    HoverSpeedPercentMultiplier,
    TurnSpeed,
    UpwardPitchCap
}