public enum EUnitFloatStats 
{ 
    //Base
    MaxHealth,
    BaseArmorPercent,
    MaxArmorPercent,
    Damage,
    CritMultiplierPercent,
    CritChancePercent,
    AttackSpeedPercent,
    MovementSpeed,
    SightRange,
    AttackRange,
    ChaseSpeedPercentMultiplier,
    //Cavalry
    ChargeEndDistance,
    ReturnSpeed,
    //Traverse
    TraverseSpeed
}